version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  frontend:
    image: node:18
    command: sh -c "npx create-react-app my-app && cd my-app && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - app_network


  backend:
    image: node:18
    command: sh -c "npm install express masql && node server.js"
    ports:
      - "5000:5000"
    depends_on:
      - dp
    environment:
      - DB_HOST=dp
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=mydatebase
    restart: always
    networks:
      - app_network


  services:
    db:
      image: mysql:8.0
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: mydatabase
      volumes:
          - db_data:/var/lib/mysql
      restart: always
      networks:
        - app_network

        
  volumes:
    db_data: